### ISSUE TITLE
SharePoint Wiki / Training Document

### ISSUE THREAD

**Issue by jwnich93** [jwnich93/Fuel-Accounting#7]
### Task List

_To create and finish fuel accounting wiki / training document - each bullet represents a section that needs to be completed._

- 

- [ ] Staffing - https://wss.inside.ups.com/sites/64/fin/Fuel%20Accounting/SitePages/Guidelines%20-%20Staffing.aspx 

- [ ] Fuel Reconciliation Methodology - https://wss.inside.ups.com/sites/64/fin/Fuel%20Accounting/SitePages/Guidelines%20-%20Reconcilation%20Methodology.aspx 

- [ ] Monthly Schedule

- [ ]  Computer Configuration (call tsg, explain issue, ip address, fix)

- [ ]  Data Entry Clerk Instructions - https://wss.inside.ups.com/sites/64/fin/Fuel%20Accounting/SitePages/Guidelines%20-%20Data%20Entry%20Fuel%20and%20Oil%20Data%20Entry.aspx

- [ ]  Fuel Island Gauges

- [ ] Vehicle Fueling

- [ ]  Fuel Drops

**Comment by jwnich93** [comment]
I need feedback from management / third party to validate my knowledge on fuel accounting practices.

**Comment by jwnich93** [comment]
### Work Log:

- 8/21/18 Edited Staffing, Reconciliation Methodology, Data Entry Sections (see links above). [1.5 hours]

**Comment by jwnich93** [comment]
### Deadline:

- [ ] 8/23/18 - Rough draft deadline - review with Jake and Danny.
